### ISSUE TITLE
Fix title

### ISSUE THREAD

**Issue by korbinib** [elixir-oslo/norwegian-life-sci-rdm-lookup#18]
fix page title everywhere to "Norwegian Life Science RDM LookUp"

**Comment by Nazeeefa** [comment]
I can take care of the titles mentioned in text.
What about the text in the logo (in top menu)? I am fine with it for now. If we update text there, we'd then also need to think about adding Norway flag/map in the logo then.

**Comment by korbinib** [comment]
I can change the logo if desired. Adding a map might work but will start to look cluttered.

**Comment by Nazeeefa** [comment]
How about just adding magnifying-glass icon after "LookUp" or as part of logo? if latter, then we can add flag as icon after the word 'LookUp' in the logo. Does that make sense? :D

**Comment by korbinib** [comment]
I tried to play with the circle as magnify glass, but it was too many details.

**Comment by korbinib** [comment]
the repo should also be renamed.

**Comment by korbinib** [comment]
fixed by https://github.com/elixir-oslo/biomeddata/commit/283c5095909cd4d71e82c53d03be7374d34ed403

the repo should still be renamed

**Comment by Nazeeefa** [comment]
I have yet to submit my changes. I will update the name once all issues are resolved (assuming the repo's name change will also effect website URL).

**Comment by Nazeeefa** [comment]
The repo is renamed. 
I have yet to submit my changes from my fork..
