### ISSUE TITLE
Main/Landing Cheat Sheet page

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-oslo/norwegian-life-sci-rdm-lookup#19]
- [x] Remove the word 'short' before cheat sheets.
- [x] Rephrase "Links to a Data Stewardship Wizard for your DMP templates" to  "Links to Data Management Plan (DMP) templates, relevant to your research domain, in Data Stewardship Wizard" (ok this is too long, feel free to ignore)
- [x] Add link to BioMedData https://elixir.no/organization/biomeddata where it says "..infrastructures within BioMedData in Norway". Maybe with 'Read more about BioMedData at: <link>"
- [x] Suggested description for page: "We provide here a set of information (cheat sheets), for various domains in life sciences, with different approaches on how they manage their data. In this section, you will find:"

**Comment by korbinib** [comment]
fix in https://github.com/elixir-oslo/norwegian-life-sci-rdm-lookup/commit/8e43d7332dc404b5b78f2c4d9a9fede2609a4904
